
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace NETMFTemperatureController
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.Display_TE35 display_TE35;
        Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        Gadgeteer.Modules.MyGadgeteerModules.ControlRelays controlRelays;
        Gadgeteer.Modules.MyGadgeteerModules.TemperatureProbe temperatureProbe;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
		
            temperatureProbe = new GTM.MyGadgeteerModules.TemperatureProbe(4);
		
            display_TE35 = new GTM.GHIElectronics.Display_TE35(14, 13, 12, 10);
		
            controlRelays = new GTM.MyGadgeteerModules.ControlRelays(11);

        }
    }
}
