//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETMFTemperatureController
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("NETMFTemperatureController.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            heating_icon_bw = -28046,
            StartScreen = -25810,
            GlassRoundDwnButtonSmall = -18189,
            cooling_icon_bw = -14853,
            idle_icon_bw = -9935,
            BlueBackGlassSmall = -8712,
            BlueGlassSettingsSmall = 3259,
            BlueGlassLagerSmall = 5164,
            GlassRoundUpButtonSmall = 8591,
            BlueGlassAleSmall = 12691,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            heatStatusText = -22040,
            dashTitle = -19308,
            currentModeLabel = -13525,
            appVersion = -7623,
            offModeText = -6727,
            errorTitle = -4971,
            unitsLabel = -2026,
            currentUnitsLabel = -616,
            setpointLabel = 412,
            celsiusUnit = 690,
            fahrenheitUnit = 2986,
            settingsTitle = 4343,
            coolStatusText = 13620,
            currentTempLabel = 15731,
            holdModeText = 16161,
            idleStatusText = 17572,
            heatModeText = 21726,
            statusLabel = 24892,
            coolModeText = 26811,
            appTitle = 28436,
            manufacturerName = 30780,
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Arial_24_Bold = -13344,
            Arial_10_Bold = 116,
            Arial_14_Bold = 8128,
            small = 13070,
            NinaB = 18060,
            Arial_16_Bold = 29136,
        }
    }
}
